# Generated by Django 5.2.15 on 2026-06-26 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        help_text="Внутренний артикул HAUSPELLA (например: HSP-000001)",
                        max_length=20,
                        unique=True,
                        verbose_name="Артикул",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Старая цена",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(blank=True, verbose_name="Краткое описание"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Полное описание"),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SEO-заголовок"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="Meta-описание"),
                ),
                (
                    "main_keyword",
                    models.CharField(
                        blank=True,
                        help_text="Основной поисковый запрос.",
                        max_length=255,
                        verbose_name="Главный поисковый запрос",
                    ),
                ),
                (
                    "search_aliases",
                    models.TextField(
                        blank=True,
                        help_text="По одному запросу на строку.",
                        verbose_name="Дополнительные поисковые запросы",
                    ),
                ),
                (
                    "competitive_advantages",
                    models.TextField(
                        blank=True,
                        help_text="Конкретные преимущества товара перед конкурентами.",
                        verbose_name="Конкурентные преимущества",
                    ),
                ),
                (
                    "unique_selling_proposition",
                    models.TextField(
                        blank=True,
                        help_text="Главная идея продажи. Что получит покупатель после покупки.",
                        verbose_name="Уникальное торговое предложение (УТП)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["article"],
            },
        ),
    ]
