# Generated by Django 5.2.15 on 2026-06-26 21:19

import apps.catalog.utils.upload_paths
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.catalog.utils.upload_paths.product_image_upload_path,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        help_text="Описание изображения для SEO и доступности.",
                        max_length=255,
                        verbose_name="ALT-текст",
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("main", "Главное"),
                            ("front", "Спереди"),
                            ("back", "Сзади"),
                            ("detail", "Деталь"),
                            ("infographic", "Инфографика"),
                            ("package", "Комплектация"),
                            ("lifestyle", "В интерьере"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Тип изображения",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Чем меньше число, тем выше изображение в галерее.",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение товара",
                "verbose_name_plural": "Изображения товаров",
                "ordering": ("sort_order", "id"),
            },
        ),
    ]
