# Generated by Django 5.2.15 on 2026-06-27 09:12

import apps.catalog.utils.upload_paths
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_productimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Название, которое будет отображаться пользователю.",
                        max_length=255,
                        verbose_name="Название документа",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.catalog.utils.upload_paths.product_document_upload_path,
                        verbose_name="PDF-документ",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("instruction", "Инструкция"),
                            ("certificate", "Сертификат"),
                            ("declaration", "Декларация"),
                            ("datasheet", "Техническая спецификация"),
                            ("warranty", "Гарантия"),
                            ("safety", "Документ по безопасности"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Тип документа",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("en", "English"),
                            ("kk", "Қазақша"),
                            ("uz", "O'zbek"),
                            ("ky", "Кыргызча"),
                            ("hy", "Հայերեն"),
                            ("ka", "ქართული"),
                            ("be", "Беларуская"),
                            ("de", "Deutsch"),
                            ("fr", "Français"),
                            ("it", "Italiano"),
                            ("es", "Español"),
                            ("pl", "Polski"),
                            ("zh", "中文"),
                            ("other", "Другое"),
                        ],
                        default="ru",
                        max_length=10,
                        verbose_name="Язык документа",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Чем меньше число, тем выше документ в списке.",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ товара",
                "verbose_name_plural": "Документы товаров",
                "ordering": ("sort_order", "id"),
            },
        ),
    ]
