# Generated by Django 5.2.15 on 2026-06-27 12:58

import apps.catalog.utils.upload_paths
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_productdocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdocument",
            name="file",
            field=models.FileField(
                upload_to=apps.catalog.utils.upload_paths.product_document_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="PDF-документ",
            ),
        ),
        migrations.CreateModel(
            name="ProductVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Название, которое будет отображаться покупателю.",
                        max_length=255,
                        verbose_name="Название видео",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Чем меньше число, тем выше видео в списке.",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Видео товара",
                "verbose_name_plural": "Видео товаров",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProductVideoSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("vk_video", "VK Видео"),
                            ("rutube", "Rutube"),
                            ("dzen_video", "Дзен Видео"),
                            ("platforma", "Платформа"),
                            ("ok_video", "Одноклассники Видео"),
                            ("kinescope", "Kinescope"),
                            ("wibes", "Wibes"),
                            ("rambler", "Рамблер"),
                            ("coub", "Coub"),
                            ("twitch", "Twitch"),
                            ("other", "Другое"),
                        ],
                        max_length=30,
                        verbose_name="Платформа",
                    ),
                ),
                ("url", models.URLField(max_length=500, verbose_name="Ссылка")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Чем меньше число, тем выше источник в списке.",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="catalog.productvideo",
                        verbose_name="Видео",
                    ),
                ),
            ],
            options={
                "verbose_name": "Источник видео",
                "verbose_name_plural": "Источники видео",
                "ordering": ("sort_order", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("video", "platform"),
                        name="unique_product_video_platform",
                    )
                ],
            },
        ),
    ]
